spring.application.name=api-notificacoes

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

app.rabbitmq.exchange=notificacoes.exchange
app.rabbitmq.queue=notificacoes.queue
app.rabbitmq.routingkey=notificacoes.routingkey