spring.application.name=api-notificacoes

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

app.rabbitmq.exchange=notificacoes.exchange
app.rabbitmq.queue=notificacoes.queue
app.rabbitmq.routingkey=notificacoes.routingkey

app.rabbitmq.dlx.exchange=notificacoes.dlx.exchange
app.rabbitmq.dlq=notificacoes.dlq
app.rabbitmq.dlq.routingkey=notificacoes.dlq.routingkey

app.rabbitmq.retry.max-attempts=3
app.rabbitmq.retry.initial-interval=1000
app.rabbitmq.retry.multiplier=2.0
app.rabbitmq.retry.max-interval=10000